uint8 pdu_proto_version 4
uint8 pdu_message_id 2
uint32 pdu_src_station_id 100

uint32 mc_action_id_origin_station_id 0
uint16 mc_action_id_seq_no 0
uint64 mc_det_time 0
uint64 mc_ref_time 0
uint32 mc_ref_pos_lattitude 0
uint32 mc_ref_pos_longitude 0
uint16 mc_ref_pos_conf_ellipse_semi_major 0
uint16 mc_ref_pos_conf_ellipse_semi_minor 0
uint16 mc_ref_pos_altitude_heading 0
uint32 mc_ref_pos_altitude_val 0
uint8 mc_ref_pos_altitude_conf 0
uint32 mc_validity_duration 0
uint8 mc_station_type 0

uint8 al_carte_type 0
uint32 al_des_station_id 0
uint16 al_rrc_timeout 0
uint8 al_rrc_reason 0
